#!/bin/sh

# less to download than using git
wget "https://github.com/nightingale-media-player/nightingale-hacking/archive/sb-trunk-oldxul.zip"

git clone https://github.com/darealshinji/minimizetotrayplus.git

unzip sb-trunk-oldxul.zip
cd nightingale-hacking-sb-trunk-oldxul/
mv debian debian-upstream

# clean up - make the source package smaller
find . -name *.mp3 -delete
rm -rf tools/win32

# download dependencies
version=1.12
depdate=`grep -e 'depdate=' build.sh | tail -c 9`
depsource=http://downloads.sourceforge.net/project/ngale/1.12-Build-Deps
cd dependencies/
wget "$depsource/linux-i686-$version-$depdate-release-final.tar.lzma"
wget "$depsource/linux-x86_64-$version-$depdate-release-final.tar.lzma"
cd ..

# copy minimizetotray extension
cp -rf ../minimizetotrayplus/nightingale-hacking/extensions/* extensions/

# download additional extensions
git clone https://github.com/nightingale-media-player/nightingale-addons.git
mkdir addons/
cd nightingale-addons/
mv make.py eqpresets equalizerpane newtab ../addons
rm -rf ../nightingale-addons
cd ../..

# create tarball
tar cvf - nightingale-hacking-sb-trunk-oldxul | xz > nightingale_1.12.2a+gitINSERTDATE.orig.tar.xz

# clean up
rm -rf \
  sb-trunk-oldxul.zip \
  nightingale-hacking-sb-trunk-oldxul \
  minimizetotrayplus
